import Foundation

/// What the fault codes of every module on the platform mean, generated by
/// `tools/diagbox/make_dtc.py` into `data/profile/dtc_B7.json`.
///
/// 15 103 codes over 74 ECUs. Every repeating part is stored once and
/// referenced by index - the description texts, the failure-type tables, and
/// the code set of a whole ECU family - which is what keeps the file to 0.7 MB
/// instead of 1.6. It is loaded off the main thread on the first fault read and
/// kept for the life of the app.
///
/// Nothing depends on it: a code it cannot name is still read, shown and
/// cleared, with the code itself standing in for the description.
struct DtcDictionary: Decodable {

    /// One fault code: the index of its description, plus the index of its
    /// failure-type table when it has one.
    enum Entry: Decodable, Equatable {
        case text(Int)
        case described(text: Int, failureTypes: Int)

        var textIndex: Int {
            switch self {
            case let .text(i): return i
            case let .described(i, _): return i
            }
        }

        var failureTypeIndex: Int? {
            switch self {
            case .text: return nil
            case let .described(_, table): return table
            }
        }

        init(from decoder: Decoder) throws {
            let c = try decoder.singleValueContainer()
            if let i = try? c.decode(Int.self) {
                self = .text(i)
                return
            }
            let pair = try c.decode([Int].self)
            guard let text = pair.first else {
                throw DecodingError.dataCorruptedError(
                    in: c, debugDescription: "пустая запись кода неисправности")
            }
            self = pair.count > 1 ? .described(text: text, failureTypes: pair[1]) : .text(text)
        }
    }

    let platform: String
    /// Readable module names, as Diagbox itself labels them in its ECU menu.
    let families: [String: String]
    /// Failure-type tables: byte -> what that failure is, for one fault code.
    let failureTypes: [[String: String]]
    /// The description texts, pooled - one sentence describes hundreds of
    /// codes across the platform.
    let texts: [String]
    /// Code sets, one per distinct list; several ECUs share one.
    let groups: [[String: Entry]]
    /// ECU name -> which code set it answers with.
    let ecus: [String: Int]

    enum CodingKeys: String, CodingKey {
        case platform
        case families = "fam"
        case failureTypes = "enum"
        case texts = "lab"
        case groups
        case ecus
    }

    // MARK: - lookup

    /// The code set of a module. An ambiguous address answers for one of
    /// several ECUs and the app cannot tell which, so take the first candidate
    /// the dictionary knows.
    func codes(forAnyOf names: [String]) -> [String: Entry]? {
        for name in names {
            if let i = ecus[name], groups.indices.contains(i) { return groups[i] }
        }
        return nil
    }

    func family(_ code: String) -> String? { families[code] }

    func text(at index: Int) -> String? {
        texts.indices.contains(index) ? texts[index] : nil
    }

    /// What the failure-type byte of one fault means, in this ECU's wording.
    func failureType(_ byte: String, of entry: Entry) -> String? {
        guard let table = entry.failureTypeIndex, failureTypes.indices.contains(table) else {
            return nil
        }
        return failureTypes[table][byte.uppercased()]
    }

    enum LoadError: Error, LocalizedError {
        case notBundled

        var errorDescription: String? {
            switch self {
            case .notBundled: return "dtc_B7.json отсутствует в сборке"
            }
        }
    }

    static func decode(_ data: Data) throws -> DtcDictionary {
        try JSONDecoder().decode(DtcDictionary.self, from: data)
    }

    static func bundled(in bundle: Bundle = .main) throws -> DtcDictionary {
        guard let url = bundle.url(forResource: "dtc_B7", withExtension: "json") else {
            throw LoadError.notBundled
        }
        return try decode(try Data(contentsOf: url))
    }
}
