import Foundation

/// The V46.21 profile as generated by tools/diagbox/make_profile.py from the
/// official Diagbox databases. The exact same JSON body is spliced into
/// index.html and bundled as an Android asset, so byte offsets, scaling and
/// text states can never differ between the three versions.
struct Profile: Decodable {
    struct CANIds: Decodable {
        let req: String
        let res: String
    }

    /// One reading inside a page's reply. `offset`/`length` index into the
    /// bytes after the page marker; the value is `raw * scale + delta`, unless
    /// `states` gives it a text meaning.
    struct Field: Decodable {
        let key: String
        let label: String
        let offset: Int
        let length: Int
        let scale: Double
        let delta: Double
        let unit: String
        let decimals: Int
        let low: Double
        let high: Double
        let states: [String: String]?
        /// Bitfield extraction: `(raw >> shift) & mask`. Only two parameters
        /// use it (the engaged gear and the gearbox type).
        let mask: Int?
        let shift: Int?
        /// Identification strings are shown as raw hex, not scaled numbers.
        let hex: Bool?

        enum CodingKeys: String, CodingKey {
            case key = "k"
            case label = "l"
            case offset = "o"
            case length = "n"
            case scale = "z"
            case delta = "d"
            case unit = "u"
            case decimals = "dec"
            case low = "lo"
            case high = "hi"
            case states = "st"
            case mask = "m"
            case shift = "sh"
            case hex
        }
    }

    /// A single request/reply pair. Live measurement pages carry an `id`;
    /// identification blocks do not.
    struct Page: Decodable {
        let id: String?
        let request: String
        let marker: String
        let title: String
        let params: [Field]
        /// Pages the ECU answers slowly; the poll loop gives them a longer
        /// period. Absent on identification blocks.
        let slow: Bool?

        enum CodingKeys: String, CodingKey {
            case id
            case request = "req"
            case marker = "mk"
            case title
            case params
            case slow
        }
    }

    let ecu: String
    let platform: String
    let can: CANIds
    let pages: [Page]
    let ident: [Page]
    let dtc: [String: String]

    var liveParamCount: Int { pages.reduce(0) { $0 + $1.params.count } }
    var identFieldCount: Int { ident.reduce(0) { $0 + $1.params.count } }

    enum LoadError: Error, LocalizedError {
        case notBundled

        var errorDescription: String? {
            switch self {
            case .notBundled: return "v46_21_profile.json отсутствует в сборке"
            }
        }
    }

    static func bundled() throws -> Profile {
        guard let url = Bundle.main.url(forResource: "v46_21_profile", withExtension: "json") else {
            throw LoadError.notBundled
        }
        return try JSONDecoder().decode(Profile.self, from: try Data(contentsOf: url))
    }
}
