import Foundation

/// The diagnostic address map of the platform, generated by
/// `tools/diagbox/make_scan.py` into `data/profile/scan_B7.json`.
///
/// This is what turns a one-ECU tool into a whole-car one: for every module the
/// B7 platform can carry it holds the CAN pair to talk on, the frame that opens
/// a session, the frame that identifies the module, and the frames that read
/// and clear its fault memory.
///
/// Several ECUs share one CAN address and answer the very same recognition
/// frame - only the identification bytes separate them, and those are not in
/// the extract - so such candidates are merged into one probe carrying every
/// possible name. The app says "one of these" rather than picking.
struct ScanProfile: Decodable {

    /// How a fault-read answer is laid out. `header` bytes of service id plus a
    /// count or an availability mask, then fixed-length records.
    struct FaultFrames: Decodable, Equatable {
        let request: String
        let answer: String
        let header: Int
        let record: Int
        let codeAt: Int
        let codeLength: Int
        let statusAt: Int

        enum CodingKeys: String, CodingKey {
            case request = "q"
            case answer = "o"
            case header = "h"
            case record = "l"
            case codeAt = "c"
            case codeLength = "cl"
            case statusAt = "s"
        }

        /// A UDS record carries one more byte between the code and the status -
        /// the failure type, which says *how* the circuit failed and is part of
        /// the code when clearing one fault on its own.
        var failureTypeAt: Int? {
            let at = codeAt + codeLength
            return at < statusAt ? at : nil
        }

        /// KWP answers `57 <count>`, so the count bounds the list. UDS answers
        /// `59 02 <availability mask>` and is bounded by the frame length alone.
        var hasCount: Bool { answer == "57" }

        /// Whether the status byte is the ISO 14229 bit field. A KWP ECU
        /// answers a byte of its own whose meaning is published nowhere, so
        /// that one is shown raw rather than guessed at.
        var statusIsStandard: Bool { answer == "5902" }
    }

    /// One probe: an address, what to say to it, and what its answers mean.
    struct Target: Decodable, Equatable, Identifiable {
        let family: String
        let name: String
        let alternatives: [String]
        let request: String
        let response: String
        /// Frame that opens a diagnostic session, and the answer's first byte.
        /// Empty for the few modules Diagbox reaches without one.
        let openSession: String
        let openAnswer: String
        /// Frame that identifies the module, and the prefix of its answer.
        let reco: String
        let recoAnswer: String
        let faults: FaultFrames?
        /// Frame that clears the whole fault memory; nil when Diagbox
        /// describes no clear for this module.
        let clear: String?

        enum CodingKeys: String, CodingKey {
            case family = "f"
            case name = "n"
            case alternatives = "alts"
            case request = "q"
            case response = "r"
            case openSession = "i"
            case openAnswer = "io"
            case reco = "rc"
            case recoAnswer = "ro"
            case faults = "d"
            case clear = "cl"
        }

        init(from decoder: Decoder) throws {
            let c = try decoder.container(keyedBy: CodingKeys.self)
            family = try c.decode(String.self, forKey: .family)
            name = try c.decode(String.self, forKey: .name)
            alternatives = try c.decodeIfPresent([String].self, forKey: .alternatives) ?? []
            request = try c.decode(String.self, forKey: .request)
            response = try c.decode(String.self, forKey: .response)
            openSession = try c.decodeIfPresent(String.self, forKey: .openSession) ?? ""
            openAnswer = try c.decodeIfPresent(String.self, forKey: .openAnswer) ?? ""
            reco = try c.decode(String.self, forKey: .reco)
            recoAnswer = try c.decode(String.self, forKey: .recoAnswer)
            faults = try c.decodeIfPresent(FaultFrames.self, forKey: .faults)
            clear = try c.decodeIfPresent(String.self, forKey: .clear)
        }

        /// Built by hand rather than decoded, for the engine on a link where
        /// there is no address map to walk, and for tests.
        init(family: String, name: String, alternatives: [String] = [],
             request: String, response: String,
             openSession: String = "", openAnswer: String = "",
             reco: String, recoAnswer: String,
             faults: FaultFrames? = nil, clear: String? = nil) {
            self.family = family
            self.name = name
            self.alternatives = alternatives
            self.request = request
            self.response = response
            self.openSession = openSession
            self.openAnswer = openAnswer
            self.reco = reco
            self.recoAnswer = recoAnswer
            self.faults = faults
            self.clear = clear
        }

        var id: String { request + "/" + name }

        /// Every ECU this probe could have reached.
        var names: [String] { [name] + alternatives }
        var ambiguous: Bool { !alternatives.isEmpty }

        /// How wide the "group of DTC" argument of the clear service is: two
        /// bytes on a KWP module (`14 FF00`), three on a UDS one
        /// (`14 FFFFFF`). Clearing one fault means putting the fault itself
        /// there instead of the "everything" group, so its width has to match.
        var clearGroupBytes: Int {
            guard let clear, clear.count > 2 else { return 0 }
            return (clear.count - 2) / 2
        }
    }

    let platform: String
    let targets: [Target]

    enum CodingKeys: String, CodingKey {
        case platform
        case targets = "ecus"
    }

    /// One CAN address and everything that might answer on it.
    struct Probe: Equatable {
        let address: String
        let targets: [Target]
    }

    /// One probe per CAN address, in the order the file gives them - which is
    /// ascending address, so the sweep reads like Diagbox's own.
    var byAddress: [Probe] {
        var order: [String] = []
        var groups: [String: [Target]] = [:]
        for target in targets {
            if groups[target.request] == nil { order.append(target.request) }
            groups[target.request, default: []].append(target)
        }
        return order.map { Probe(address: $0, targets: groups[$0] ?? []) }
    }

    /// The same list narrowed to the modules a car was found to have.
    ///
    /// The map covers every variant of the platform, so a car answers on a
    /// fraction of it and the rest is paid for in adapter timeouts - about a
    /// minute of them. Once a full sweep has said which addresses are fitted,
    /// later sweeps walk only those, and only the candidate that answered
    /// rather than all of an address's candidates.
    func probes(fittedTo inventory: [String: String]) -> [Probe] {
        byAddress.compactMap { probe in
            guard let name = inventory[probe.address] else { return nil }
            let narrowed = probe.targets.filter { $0.name == name }
            return narrowed.isEmpty ? probe : Probe(address: probe.address, targets: narrowed)
        }
    }

    enum LoadError: Error, LocalizedError {
        case notBundled

        var errorDescription: String? {
            switch self {
            case .notBundled: return "scan_B7.json отсутствует в сборке"
            }
        }
    }

    static func decode(_ data: Data) throws -> ScanProfile {
        try JSONDecoder().decode(ScanProfile.self, from: data)
    }

    /// Loads the copy bundled with the app. `bundle` is a parameter so tests
    /// can load their own copy without a host application.
    static func bundled(in bundle: Bundle = .main) throws -> ScanProfile {
        guard let url = bundle.url(forResource: "scan_B7", withExtension: "json") else {
            throw LoadError.notBundled
        }
        return try decode(try Data(contentsOf: url))
    }
}
