"""Render the platform ECU inventory into the scan profile the app embeds.

    python make_scan.py --vehicle-json ../../data/diagbox/vehicle_B7.json \
        --out ../../data/diagbox/scan_B7.js --inject ../../index.html

One entry per candidate ECU: CAN identifiers, the frame that opens a session,
the frame that identifies the ECU, and the fault read/clear frames with the
record layout. Several candidates share one CAN address (only one of them is
actually fitted), so the scanner probes an address until one answers.
"""
import argparse
import json
import os

# Families that are not really separate modules, or that Diagbox reaches
# through another ECU rather than by their own diagnostic address.
SKIP_PROTOCOLS = {'RAW_CAN'}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--vehicle-json', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('--inject')
    a = ap.parse_args()

    with open(a.vehicle_json, encoding='utf-8') as fh:
        veh = json.load(fh)

    # Several ECUs sit on one address and answer the very same recognition
    # frame - the identification bytes tell them apart, and those are not in
    # this extract. Merge such candidates into one entry with every possible
    # name rather than reporting the first as if it were certain.
    groups, order = {}, []
    for e in veh['ecus']:
        f = e.get('frames') or {}
        can = e['can']
        if not can['request_id'] or not can['response_id']:
            continue
        if e.get('protocol') in SKIP_PROTOCOLS:
            continue
        if not f.get('reco_request') or not f.get('reco_answer'):
            continue
        fl = e.get('faults') or {}
        read = fl.get('read') or {}
        key = (can['request_id'], can['response_id'],
               f.get('init_request') or '', f['reco_request'],
               read.get('request'))
        row = groups.get(key)
        if row is None:
            row = groups[key] = {
                'f': e['family'], 'n': e['ecu'], 'alts': [],
                'q': can['request_id'], 'r': can['response_id'],
                'i': f.get('init_request') or '',
                'io': f.get('init_answer') or '',
                'rc': f['reco_request'], 'ro': f['reco_answer'],
            }
            order.append(row)
            if read:
                row['d'] = {'q': read['request'], 'o': read['answer'],
                            'h': read['header'], 'l': read['record'],
                            'c': read['code_at'], 'cl': read['code_len'],
                            's': read['status_at']}
            if fl.get('clear'):
                row['cl'] = fl['clear']['request']
                row['clo'] = fl['clear']['answer']
        elif e['ecu'] != row['n'] and e['ecu'] not in row['alts']:
            row['alts'].append(e['ecu'])

    ecus = order
    for row in ecus:
        if not row['alts']:
            del row['alts']
    ecus.sort(key=lambda x: (x['q'], x['f'], x['n']))
    profile = {'platform': veh['platform'], 'ecus': ecus}
    body = json.dumps(profile, ensure_ascii=False, separators=(',', ':'))
    decl = 'const V4621_SCAN = %s;\n' % body

    os.makedirs(os.path.dirname(a.out) or '.', exist_ok=True)
    with open(a.out, 'w', encoding='utf-8') as fh:
        fh.write(decl)

    if a.inject:
        head = '/* === SCAN PROFILE (generated by tools/diagbox/' \
               'make_scan.py - do not edit by hand) === */\n'
        tail = '/* === END SCAN PROFILE === */'
        with open(a.inject, encoding='utf-8') as fh:
            page = fh.read()
        i, j = page.index(head), page.index(tail)
        page = page[:i] + head + decl + page[j:]
        with open(a.inject, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(page)
        print('injected into %s' % a.inject)

    addrs = len({e['q'] for e in ecus})
    named = sum(1 for e in ecus if 'alts' not in e)
    print('%d probes on %d CAN addresses (%d identify one ECU, the rest are '
          'ambiguous), %d with fault frames -> %.0f kB'
          % (len(ecus), addrs, named, sum(1 for e in ecus if 'd' in e),
             len(body.encode('utf-8')) / 1024))


if __name__ == '__main__':
    main()
