#!/usr/bin/env python3
"""Keep the standard OBD-II parameter set in one place.

Unlike the V46.21 profile, this table is not mined from Diagbox - the formulas
are the standard's own, and only PIDs verified supported on this car
(`0100` -> `BE 3E B8 11`) are in it. It used to be written by hand inside
index.html; now `data/obd2/obd2.json` is the source and this script splices the
JavaScript form back in, so the iOS app can bundle the very same file instead of
carrying a second copy.

    python tools/obd2/make_obd2.py --check            # does the JSON still reproduce index.html?
    python tools/obd2/make_obd2.py --inject index.html
"""

import argparse
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SOURCE = os.path.join(ROOT, 'data', 'obd2', 'obd2.json')

HEAD = ('/* === OBD2 SET (generated by tools/obd2/make_obd2.py - '
        'do not edit by hand) === */\n')
TAIL = '/* === END OBD2 SET === */'


def number(value):
    """Print 1 as `1` and 0.25 as `0.25`, the way the file already has them."""
    return repr(value) if isinstance(value, float) else str(value)


def code_lines(doc):
    """The PO(...) calls, one per parameter."""
    out = []
    for p in doc['params']:
        out.append('  PO(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s),' % (
            json.dumps(p['k'], ensure_ascii=False),
            json.dumps(p['l'], ensure_ascii=False),
            json.dumps(p['pid'], ensure_ascii=False),
            number(p['n']), number(p['z']), number(p['d']),
            json.dumps(p['u'], ensure_ascii=False),
            number(p['lo']), number(p['hi']), number(p['dec']),
        ))
    return out


def block(doc):
    body = []
    for p, line in zip(doc['params'], code_lines(doc)):
        if p.get('note'):
            body.append('  // --- %s ---' % p['note'])
        body.append(line)
    return 'const OBD2=[\n' + '\n'.join(body) + '\n];\n'


def current_code_lines(html):
    """The PO(...) calls index.html holds right now, comments dropped."""
    found = re.search(r'const OBD2=\[\n(.*?)\n\];', html, re.S)
    if not found:
        return None
    return [ln for ln in found.group(1).split('\n')
            if not ln.strip().startswith('//')]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--source', default=SOURCE)
    ap.add_argument('--inject', help='index.html to splice the set into')
    ap.add_argument('--check', action='store_true',
                    help='verify the JSON reproduces what index.html holds')
    a = ap.parse_args()

    doc = json.load(io.open(a.source, encoding='utf-8'))

    if a.check:
        html = io.open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()
        have = current_code_lines(html)
        if have is None:
            print('index.html has no OBD2 array to compare against')
            return 1
        want = code_lines(doc)
        if have == want:
            print('index.html matches the JSON: %d PIDs' % len(want))
            return 0
        print('the JSON does not reproduce index.html:')
        for line in set(have) ^ set(want):
            print('  %s %s' % ('-' if line in have else '+', line.strip()))
        return 1

    text = block(doc)
    if a.inject:
        html = io.open(a.inject, encoding='utf-8').read()
        if HEAD in html:
            i = html.index(HEAD)
            j = html.index(TAIL)
            html = html[:i] + HEAD + text + html[j:]
        else:
            # First run: put the markers around the hand-written array.
            html = re.sub(r'const OBD2=\[\n.*?\n\];\n',
                          HEAD + text + TAIL + '\n', html, count=1, flags=re.S)
        io.open(a.inject, 'w', encoding='utf-8', newline='\n').write(html)
        print('injected %d PIDs into %s' % (len(doc['params']), a.inject))
    else:
        sys.stdout.write(text)
    return 0


if __name__ == '__main__':
    sys.exit(main())
